=== bwagner/dtbooktosbsform/test_xsl/utfx_tests.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 $Id: utfx_tests.dtd,v 1.8.2.3 2006/08/09 13:01:41 lachdrache Exp $
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 $Source: /cvs/utf-x/framework/src/dtd/utfx_tests.dtd,v $
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 $Name: release_0_0_8_alpha $
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

 Copyright (C) 2004-2006 UTF-X Development team.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

 UTF-X test definition file (TDF) Document Type Definition

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-->

<!ELEMENT utfx:tests (utfx:stylesheet, utfx:css?, utfx:source-validation?,
                      utfx:expected-validation?,
                      utfx:source-builder?, utfx:test*)>

<!ATTLIST utfx:tests xmlns:utfx CDATA #REQUIRED>

<!ELEMENT utfx:stylesheet EMPTY>

<!ATTLIST utfx:stylesheet src CDATA #REQUIRED
                          output (xhtml | fo) #IMPLIED>

<!ELEMENT utfx:css EMPTY>

<!ATTLIST utfx:css uri CDATA #REQUIRED>

<!ELEMENT utfx:source-validation (utfx:dtd) >

<!ELEMENT utfx:expected-validation (utfx:dtd) >

<!ELEMENT utfx:dtd EMPTY>

<!ATTLIST utfx:dtd public CDATA #IMPLIED
		           system CDATA #REQUIRED>

<!ELEMENT utfx:source-builder (utfx:class-name, utfx:constructor-params)>

<!ELEMENT utfx:class-name (#PCDATA)>

<!ELEMENT utfx:constructor-params (utfx:param*)>

<!ELEMENT utfx:param (#PCDATA)>

<!ATTLIST utfx:param type (String | Integer | Boolean | Double) "String">

<!ELEMENT utfx:test (utfx:name, utfx:stylesheet-params?, utfx:source-builder?, 
                     utfx:call-template?, utfx:assert-equal)>

<!ELEMENT utfx:stylesheet-params (utfx:with-param*)>

<!ELEMENT utfx:call-template (utfx:with-param*)>

<!ATTLIST utfx:call-template name CDATA #REQUIRED>

<!ELEMENT utfx:with-param ANY>

<!ATTLIST utfx:with-param name CDATA #REQUIRED>

<!ATTLIST utfx:with-param select CDATA #IMPLIED>

<!ELEMENT utfx:name (#PCDATA)>

<!ELEMENT utfx:assert-equal (utfx:source, utfx:expected, utfx:message?)>

<!ELEMENT utfx:source ANY>

<!ATTLIST utfx:source validate (yes | no) "yes"
                      use-source-parser (yes | no) "no"
                      xml:space (preserve | default) "preserve"
                      context-node CDATA #IMPLIED>

<!ELEMENT utfx:expected ANY>

<!ATTLIST utfx:expected validate (yes | no) "yes"
                        xml:space (preserve | default) "preserve">

<!ELEMENT utfx:message (#PCDATA)>

=== bwagner/dtbooktosbsform/test_xsl/computerBraille_test.xml
<?xml version='1.0' encoding='utf-8'?>

<!-- Copyright (C) 2011 Swiss Library for the Blind, Visually Impaired and Print Disabled -->

<!-- This file is part of dtbook2sbsform. -->

<!-- dtbook2sbsform is free software: you can redistribute it -->
<!-- and/or modify it under the terms of the GNU Lesser General Public -->
<!-- License as published by the Free Software Foundation, either -->
<!-- version 3 of the License, or (at your option) any later version. -->

<!-- This program is distributed in the hope that it will be useful, -->
<!-- but WITHOUT ANY WARRANTY; without even the implied warranty of -->
<!-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU -->
<!-- Lesser General Public License for more details. -->

<!-- You should have received a copy of the GNU Lesser General Public -->
<!-- License along with this program. If not, see -->
<!-- <http://www.gnu.org/licenses/>. -->

<!DOCTYPE utfx:tests PUBLIC "-//UTF-X//DTD utfx-tests 1.0//EN" "utfx_tests.dtd">
<utfx:tests xmlns:utfx="http://utfx.org/test-definition"
  xmlns:dtb="http://www.daisy.org/z3986/2005/dtbook/"
  xmlns:brl="http://www.daisy.org/z3986/2009/braille/">
  <utfx:stylesheet src="xsl/dtbook2sbsform.xsl"/>

  <utfx:test>
    <utfx:name>Computer Braille</utfx:name>
    <utfx:stylesheet-params>
      <utfx:with-param name="contraction" select="2"/>
    </utfx:stylesheet-params>
    <utfx:assert-equal>
      <utfx:source>
        <dtb:a xml:lang="de">www.xyz.ch</dtb:a>
      </utfx:source>
      <utfx:expected>'$WWW.XYZ.CH</utfx:expected>
    </utfx:assert-equal>
  </utfx:test>
  
</utfx:tests>

=== bwagner/dtbooktosbsform/test_xsl/dash_inside_em_test.xml
<?xml version='1.0' encoding='utf-8'?>

<!-- Copyright (C) 2011 Swiss Library for the Blind, Visually Impaired and Print Disabled -->

<!-- This file is part of dtbooksbsform. -->

<!-- dtbooksbsform is free software: you can redistribute it -->
<!-- and/or modify it under the terms of the GNU Lesser General Public -->
<!-- License as published by the Free Software Foundation, either -->
<!-- version 3 of the License, or (at your option) any later version. -->

<!-- This program is distributed in the hope that it will be useful, -->
<!-- but WITHOUT ANY WARRANTY; without even the implied warranty of -->
<!-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU -->
<!-- Lesser General Public License for more details. -->

<!-- You should have received a copy of the GNU Lesser General Public -->
<!-- License along with this program. If not, see -->
<!-- <http://www.gnu.org/licenses/>. -->

<!DOCTYPE utfx:tests PUBLIC "-//UTF-X//DTD utfx-tests 1.0//EN" "utfx_tests.dtd">
<utfx:tests xmlns:utfx="http://utfx.org/test-definition"
  xmlns:dtb="http://www.daisy.org/z3986/2005/dtbook/"
  xmlns:brl="http://www.daisy.org/z3986/2009/braille/">
  <utfx:stylesheet src="xsl/dtbook2sbsform.xsl"/>

  <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
  <!-- test for <em> starting or ending with dash -->
  <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
  <!-- Expected Failure -->
  <!-- There is still a bug here with the - in that it puts a hyphen
       mark after the -. This is apparently related to the liblouis
       tables not to the xsl -->
  <!-- <utfx:test> -->
  <!--   <utfx:name>test for &lt;em&gt; starting with dash</utfx:name> -->
  <!--   <utfx:stylesheet-params> -->
  <!--     <utfx:with-param name="contraction" select="0"/> -->
  <!--   </utfx:stylesheet-params> -->
  <!--   <utfx:assert-equal> -->
  <!--     <utfx:source> -->
  <!--       <stub xml:lang="de">auf<dtb:em>fallen</dtb:em> und <dtb:em>-steigen</dtb:em> </stub> -->
  <!--     </utfx:source> -->
  <!--     <utfx:expected>AUF'_FALLEN UND '-_STEIGEN </utfx:expected> -->
  <!--   </utfx:assert-equal> -->
  <!-- </utfx:test> -->

  <!-- Expected Failure -->
  <!-- There is still a bug here with the - in that it puts a hyphen
       mark after the -. This is apparently related to the liblouis
       tables not to the xsl -->
  <!-- <utfx:test> -->
  <!--   <utfx:name>test for &lt;em&gt; ending with dash</utfx:name> -->
  <!--   <utfx:stylesheet-params> -->
  <!--     <utfx:with-param name="contraction" select="0"/> -->
  <!--   </utfx:stylesheet-params> -->
  <!--   <utfx:assert-equal> -->
  <!--     <utfx:source> -->
  <!--       <stub xml:lang="de"><dtb:em>hin-</dtb:em> und <dtb:em>her</dtb:em>gehen </stub> -->
  <!--     </utfx:source> -->
  <!--     <utfx:expected>_HIN- UND _HER'.GEHEN</utfx:expected> -->
  <!--   </utfx:assert-equal> -->
  <!-- </utfx:test> -->

  <utfx:test>
    <utfx:name>test for text starting with space followed by dash</utfx:name>
    <utfx:stylesheet-params>
      <utfx:with-param name="contraction" select="0"/>
    </utfx:stylesheet-params>
    <utfx:assert-equal>
      <utfx:source>
        <dtb:p xml:lang="de"> -steigen</dtb:p>
      </utfx:source>
      <utfx:expected>y P&#13;  '-STEIGEN</utfx:expected>
    </utfx:assert-equal>
  </utfx:test>

</utfx:tests>
